- name: Configure Docker on EC2 Instances
  hosts: all
  become: true
  tasks:
    - name: Update package list
      apt:
        update_cache: yes

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Start Docker Service
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Deploy Docker Container
      docker_container:
        name: medicure
        image: mujahed/medicure:1.0
        state: started
        ports:
          - "8084:8082"
