DELETE FROM DOCTOR;
-- INSERT INTO DOCTOR (DOCTOR_REGISTRATION_ID,DOCTOR_NAME,DOCTOR_SPECIALITY,DOCTOR_EXPERIENCE) VALUES (DOCTOR_REGISTRATION_ID,DOCTOR_NAME,DOCTOR_SPECIALITY,DOCTOR_EXPERIENCE);
-- INSERT INTO DOCTOR (DOCTOR_REGISTRATION_ID,DOCTOR_NAME,DOCTOR_SPECIALITY,DOCTOR_EXPERIENCE) VALUES("MP1111","AAA","Neurologist","20 Years");
-- INSERT INTO DOCTOR (DOCTOR_REGISTRATION_ID,DOCTOR_NAME,DOCTOR_SPECIALITY,DOCTOR_EXPERIENCE) VALUES("MP1112","BBB","Neurologist","21 Years");
-- INSERT INTO DOCTOR (DOCTOR_REGISTRATION_ID,DOCTOR_NAME,DOCTOR_SPECIALITY,DOCTOR_EXPERIENCE) VALUES("MP1113","CCC","Neurologist","22 Years");
-- INSERT INTO DOCTOR (DOCTOR_REGISTRATION_ID,DOCTOR_NAME,DOCTOR_SPECIALITY,DOCTOR_EXPERIENCE) VALUES("MP1114","DDD","Neurologist","23 Years");